### ISSUE TITLE
User can add tags to an entry.

### ISSUE THREAD

**Issue by yunx2** [yunx2/code-journal#10]
## 📐 Plan

Entry objects have a new tags property that holds an array of tags, dom updated accordingly

## ✅ Task List

- [ ] Entry form and edit view should have interface for add/removing tags
- [ ] Objects have an array of tags associated with them that is added to or taken from; start with an empty array
- [ ] tags should appear beneath entry 
- [ ] in entries view clicking on a tag should show dialog; user can then choose to delete tag or not
- [ ] changes to data should be reflected on oage
