### ISSUE TITLE
User can sort their entries by date created.

### ISSUE THREAD

**Issue by yunx2** [yunx2/code-journal#9]
## 💰 Motivation

Coders will want to capture tidbits they pick up during their research.

## 📐 Plan

Create a responsive form that allows users to store an image URL with some notes about a specific topic.

## ✅ Task List

- [ ] Add a date property with timestamp when object is created
- [ ]  the date is visible when viewing the entry with the text 'posted on' and then a formatted date
- [ ]  editing an entry replaces the date property with a new timestamp and changes the 'posted on' text to 'edited on'
- [ ] Add dropdown to entries view 
  - [ ] user can choose from dropdown to sort entries oldest first/most recent first/ date of last edit
